//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "club")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub club_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::athlete::Entity")]
    Athlete,
    #[sea_orm(has_many = "super::coach::Entity")]
    Coach,
}

impl Related<super::athlete::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Athlete.def()
    }
}

impl Related<super::coach::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coach.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
