//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

/*
pub use super::club::Entity as Club;
pub use super::club_member::Entity as ClubMember;
pub use super::session::Entity as Session;
pub use super::skill::Entity as Skill;
pub use super::turn::Entity as Turn;
pub use super::user::Entity as User;
*/
